# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"getBIT_Status": "00_db110.ipynb",
         "getFieldNames": "00_db110.ipynb",
         "readMS110": "01_ms110.ipynb"}

modules = ["db110.py",
           "ms110.py"]

doc_url = "https://philescandon.github.io/isr/"

git_url = "https://github.com/philescandon/isr/tree/master/"

def custom_doc_links(name): return None
