# AUTOGENERATED! DO NOT EDIT! File to edit: 00_db110.ipynb (unless otherwise specified).

__all__ = ['readDB110', 'getFieldNames']

# Cell
import pandas as pd
import numpy as np
import regex
import string
#import ipdb
from pandas import DataFrame
import matplotlib.pyplot as plt
import time



# Cell
def readDB110():
    "Simple function to test"
    return 'DB110 Test'

# Cell
def getFieldNames(logfile):
    "Returns field names from a db110 datalog collected by GTS"
    nameList = []
    fields = []
    pattern = r'#\s\d*\s(?P<field>\w.*)'
    fieldsRegex = regex.compile(pattern)
    #fieldsRegex = regex.compile(pattern)
    fh = open(logfile,'r')
    lines = fh.readlines()
    for line in lines:
        m = fieldsRegex.search(line)
        if m:
            field = m.group('field')
            field = field.replace(' ','_')
            field = field.replace(':','.')
            field = field.replace('.','_')
            nameList.append(field)
        else:
            pass
    fh.close()
    #debug_here()
    # try a list here in prep for pandas

    # this looks like a set up for my matlab routines
    #fieldNames = list(enumerate(nameList))

    # how about this
    fieldNames = nameList

    # need a dictionary?
    #fieldNames = dict.fromkeys(nameList)

    return fieldNames